//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSC2011_T_STOCK_DETAIL
    {
        public int ID { get; set; }
        public System.DateTime YEAR_MONTH { get; set; }
        public string ITEM_CODE { get; set; }
        public string HEAT_NO { get; set; }
        public string LOCATION_CODE { get; set; }
        public Nullable<System.DateTime> STOCK_IN_DATE { get; set; }
        public Nullable<int> UPDATE_TYPE { get; set; }
        public string STOCK_IO_TYPE { get; set; }
        public Nullable<decimal> QTY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USER_ID { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_USER_ID { get; set; }
    }
}
