//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSC2050_T_STOCKTAKING_INSTRUCTION
    {
        public System.DateTime STOCKTAKING_DATE { get; set; }
        public string LOCATION_CODE { get; set; }
        public string ITEM_CODE { get; set; }
        public string HEAT_NO { get; set; }
        public byte STATUS { get; set; }
        public decimal STOCK_QTY { get; set; }
        public decimal ACTUAL_QTY { get; set; }
        public decimal OD { get; set; }
        public decimal WT { get; set; }
        public decimal LT { get; set; }
        public string GRADE_NAME { get; set; }
        public string MAKER_NAME { get; set; }
        public string REMARK { get; set; }
        public decimal WEIGHT { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USER_ID { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_USER_ID { get; set; }
    }
}
