//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSC2310_T_STOCK_CHECK
    {
        public decimal STOCK_CHECK_ID { get; set; }
        public System.DateTime STOCK_CHECK_DATE { get; set; }
        public string YARD { get; set; }
        public string LOCATION_CODE { get; set; }
        public string ITEM_CODE { get; set; }
        public string HEAT_NO { get; set; }
        public decimal QTY { get; set; }
        public Nullable<decimal> ACTUAL_QTY { get; set; }
        public int STATUS { get; set; }
        public string REMARK { get; set; }
        public string CREATE_USER_ID { get; set; }
        public System.DateTime CREATE_DATE { get; set; }
        public string UPDATE_USER_ID { get; set; }
        public System.DateTime UPDATE_DATE { get; set; }
    }
}
