//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSC2111_T_RECEIVING_INSTRUCTION_DETAIL
    {
        public int RECEIVE_ID { get; set; }
        public string ITEM_CODE { get; set; }
        public string HEAT_NO { get; set; }
        public decimal QTY { get; set; }
        public Nullable<decimal> ACTUAL_QTY { get; set; }
        public string LOCATION_CODE { get; set; }
        public Nullable<decimal> BUNDLES { get; set; }
        public int TRAN_NO { get; set; }
        public string PO_NO { get; set; }
        public int STATUS { get; set; }
        public string REMARK { get; set; }
        public string CREATE_USER_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string UPDATE_USER_ID { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    }
    public partial class PSC2113_T_RECEIVING_INSTRUCTION_ADJUST
    {
        public int RECEIVE_ID { get; set; }
        public string ITEM_CODE { get; set; }
        public string HEAT_NO { get; set; }
        public decimal QTY { get; set; }
        public Nullable<decimal> ACTUAL_QTY { get; set; }
        public string LOCATION_CODE { get; set; }
        public Nullable<decimal> BUNDLES { get; set; }
        public int TRAN_NO { get; set; }
        public string PO_NO { get; set; }
        public int STATUS { get; set; }
        public string REMARK { get; set; }
        public string CREATE_USER_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string UPDATE_USER_ID { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public Nullable<decimal> QTY_CHANGE { get; set; }
        public string LOCATION_CHANGE { get; set; }
    }
}
