//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSC2411_T_RELEASE_DETAIL
    {
        public decimal RELEASE_ID { get; set; }
        public string ITEM_CODE { get; set; }
        public string HEAT_NO { get; set; }
        public string REQUEST_NO { get; set; }
        public System.DateTime REQUEST_DATE { get; set; }
        public Nullable<System.DateTime> RECEIVE_DATE { get; set; }
        public Nullable<decimal> REQUEST_QTY { get; set; }
        public Nullable<decimal> ACTUAL_QTY { get; set; }
        public Nullable<byte> STATUS { get; set; }
        public string Y2_REMARK { get; set; }
        public string Y1_REMARK { get; set; }
        public string C_REMARK { get; set; }
        public string CREATE_USER_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string UPDATE_USER_ID { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    }

    public partial class PSC2414_T_RELEASE_HISTORY
    {
        public decimal RELEASE_ID { get; set; }
        public string JOB_NO { get; set; }
        public string MFG_NO { get; set; }
        public string ITEM_CODE { get; set; }
        public string HEAT_NO { get; set; }
        public Nullable<decimal> REQUEST_QTY { get; set; }
        public Nullable<decimal> RELEASE_QTY { get; set; }
        public Nullable<decimal> REQUEST_CHANGE { get; set; }
        public Nullable<decimal> RELEASE_CHANGE { get; set; }
        public Nullable<byte> STATUS { get; set; }
        public string CREATE_USER_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string UPDATE_USER_ID { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    }

    public partial class PSC2415_T_DELETE_HISTORY
    {
        public decimal DEL_ID { get; set; }
        public string JOB_NO { get; set; }
        public string MFG_NO { get; set; }
        public string ITEM_CODE { get; set; }
        public string HEAT_NO { get; set; }
        public string DESCRIPTION { get; set; }
        public string Product { get; set; }
        public decimal RELEASE_QTY { get; set; }
        public Nullable<byte> STATUS { get; set; }
        public string CREATE_USER_ID { get; set; }
        public string UPDATE_USER_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    }
}
