//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSC2010_T_STOCK
    {
        public System.DateTime YEAR_MONTH { get; set; }
        public string ITEM_CODE { get; set; }
        public string HEAT_NO { get; set; }
        public string LOCATION_CODE { get; set; }
        public Nullable<decimal> STOCK_START_QTY { get; set; }
        public Nullable<decimal> STOCK_IN_QTY { get; set; }
        public Nullable<decimal> STOCK_OUT_QTY { get; set; }
        public Nullable<decimal> STOCK_ADJUST_IN_QTY { get; set; }
        public Nullable<decimal> STOCK_ADJUST_OUT_QTY { get; set; }
        public Nullable<decimal> STOCK_QTY { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USER_ID { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_USER_ID { get; set; }
    }
}
