//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSC3200_T_SYTELINE_PIPE_ITEM
    {
        public float TRANS_NO { get; set; }
        public string ITEM_CODE { get; set; }
        public string HEAT_NO { get; set; }
        public string DESCRIPTION { get; set; }
        public string OD { get; set; }
        public string WT { get; set; }
        public string LT { get; set; }
        public Nullable<decimal> UNIT_WEIGHT { get; set; }
        public string MATERIAL { get; set; }
        public string MATERIAL_NAME { get; set; }
        public string STANDARD { get; set; }
        public string STANDARD_NAME { get; set; }
        public string GRADE { get; set; }
        public string GRADE_NAME { get; set; }
        public string SHAPE { get; set; }
        public string SHAPE_NAME { get; set; }
        public string MAKER { get; set; }
        public string MAKER_NAME { get; set; }
        public string LABEL1 { get; set; }
        public string ATTRIBUTE1 { get; set; }
        public string LABEL2 { get; set; }
        public string ATTRIBUTE2 { get; set; }
        public string LABEL3 { get; set; }
        public string ATTRIBUTE3 { get; set; }
        public string LABEL4 { get; set; }
        public string ATTRIBUTE4 { get; set; }
        public string LABEL5 { get; set; }
        public string ATTRIBUTE5 { get; set; }
        public string LABEL6 { get; set; }
        public string ATTRIBUTE6 { get; set; }
        public string LABEL7 { get; set; }
        public string ATTRIBUTE7 { get; set; }
        public string LABEL8 { get; set; }
        public string ATTRIBUTE8 { get; set; }
        public string LABEL9 { get; set; }
        public string ATTRIBUTE9 { get; set; }
        public string LABEL10 { get; set; }
        public string ATTRIBUTE10 { get; set; }
        public string CREATE_USER_ID { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string UPDATE_USER_ID { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
    }
}
