//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSC8011_M_PIPE_LABEL_SEQ
    {
        public string ITEM_CODE { get; set; }
        public string HEAT_NO { get; set; }
        public string SEQ_NO { get; set; }
    }
}
