//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSC8010_M_PIPE
    {
        public string ITEM_CODE { get; set; }
        public string HEAT_NO { get; set; }
        public Nullable<decimal> UNIT_WEIGHT { get; set; }
        public string MATERIAL { get; set; }
        public string MATERIAL_NAME { get; set; }
        public string STANDARD { get; set; }
        public string STANDARD_NAME { get; set; }
        public string GRADE { get; set; }
        public string GRADE_NAME { get; set; }
        public string SHAPE { get; set; }
        public string SHAPE_NAME { get; set; }
        public Nullable<decimal> OD { get; set; }
        public Nullable<decimal> WT { get; set; }
        public Nullable<decimal> LT { get; set; }
        public string MAKER { get; set; }
        public string MAKER_NAME { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USER_ID { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_USER_ID { get; set; }
    }
}
