//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSCS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PSC9020_T_PIPE_LABEL_ISSUE_HISTORY
    {
        public string ITEM_CODE { get; set; }
        public string HEAT_NO { get; set; }
        public string SEQ_NO { get; set; }
        public Nullable<System.DateTime> RECEIVED_DATE { get; set; }
        public string PIPE_SPEC { get; set; }
        public Nullable<decimal> OD { get; set; }
        public Nullable<decimal> WT { get; set; }
        public Nullable<decimal> LT { get; set; }
        public string MAKER_NAME { get; set; }
        public Nullable<decimal> BUNDLES { get; set; }
        public Nullable<decimal> ISSUE_AMOUNT { get; set; }
        public Nullable<byte> IS_BUNDLED { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USER_ID { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_USER_ID { get; set; }
    }
}
