//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSCS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class PSCSEntities : DbContext
    {
        public PSCSEntities()
            : base("name=PSCSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<PSC2010_T_STOCK> PSC2010_T_STOCK { get; set; }
        public DbSet<PSC2050_T_STOCKTAKING_INSTRUCTION> PSC2050_T_STOCKTAKING_INSTRUCTION { get; set; }
        public DbSet<PSC9020_T_PIPE_LABEL_ISSUE_HISTORY> PSC9020_T_PIPE_LABEL_ISSUE_HISTORY { get; set; }
        public DbSet<PSC9030_T_RELEASE_DATA> PSC9030_T_RELEASE_DATA { get; set; }
        public DbSet<PSC8020_M_LOCATION> PSC8020_M_LOCATION { get; set; }
        public DbSet<PSC8021_M_PLACE> PSC8021_M_PLACE { get; set; }
        public DbSet<PSC8022_M_YARD> PSC8022_M_YARD { get; set; }
        public DbSet<PSC8050_M_COMMON> PSC8050_M_COMMON { get; set; }
        public DbSet<PSC8030_M_USER> PSC8030_M_USER { get; set; }
        public DbSet<PSC8040_M_ROLE> PSC8040_M_ROLE { get; set; }
        public DbSet<PSC2110_T_RECEIVING_INSTRUCTION> PSC2110_T_RECEIVING_INSTRUCTION { get; set; }
        public DbSet<PSC3100_T_SYTELINE_NEW_PIPE> PSC3100_T_SYTELINE_NEW_PIPE { get; set; }
        public DbSet<PSC3200_T_SYTELINE_PIPE_ITEM> PSC3200_T_SYTELINE_PIPE_ITEM { get; set; }
        public DbSet<PSC8023_M_MATERIAL> PSC8023_M_MATERIAL { get; set; }
        public DbSet<PSC8025_M_GRADE> PSC8025_M_GRADE { get; set; }
        public DbSet<PSC8026_M_SHAPE> PSC8026_M_SHAPE { get; set; }
        public DbSet<PSC8027_M_MAKER> PSC8027_M_MAKER { get; set; }
        public DbSet<PSC8024_M_STANDARD> PSC8024_M_STANDARD { get; set; }
        public DbSet<PSC2300_T_HHT_STOCK_CHECK> PSC2300_T_HHT_STOCK_CHECK { get; set; }
        public DbSet<PSC2310_T_STOCK_CHECK> PSC2310_T_STOCK_CHECK { get; set; }
        public DbSet<PSC2100_T_HHT_RECEIVE> PSC2100_T_HHT_RECEIVE { get; set; }
        public DbSet<PSC2200_T_HHT_MOVE_OUT> PSC2200_T_HHT_MOVE_OUT { get; set; }
        public DbSet<PSC2400_T_HHT_RELEASE> PSC2400_T_HHT_RELEASE { get; set; }
        public DbSet<PSC3300_T_SYTELINE_JOB_MASTER> PSC3300_T_SYTELINE_JOB_MASTER { get; set; }
        public DbSet<PSC8010_M_PIPE> PSC8010_M_PIPE { get; set; }
        public DbSet<PSC8011_M_PIPE_LABEL_SEQ> PSC8011_M_PIPE_LABEL_SEQ { get; set; }
        public DbSet<PSC2200_T_HHT_MOVE_IN> PSC2200_T_HHT_MOVE_IN { get; set; }
        public DbSet<PSC2111_T_RECEIVING_INSTRUCTION_DETAIL> PSC2111_T_RECEIVING_INSTRUCTION_DETAIL { get; set; }
        public DbSet<PSC2113_T_RECEIVING_INSTRUCTION_ADJUST> PSC2113_T_RECEIVING_INSTRUCTION_ADJUST { get; set; }
        public DbSet<PSC2110_T_HHT_RECEIVE> PSC2110_T_HHT_RECEIVE { get; set; }
        public DbSet<PSC2410_T_RELEASE> PSC2410_T_RELEASE { get; set; }
        public DbSet<PSC2420_T_REQUEST> PSC2420_T_REQUEST { get; set; }
        public DbSet<PSC3010_M_MONTHLY_CLOSE> PSC3010_M_MONTHLY_CLOSE { get; set; }
        public DbSet<PSC2310_T_HHT_STOCK_CHECK> PSC2310_T_HHT_STOCK_CHECK { get; set; }
        public DbSet<PSC2412_T_RELEASE_LOCATION_DETAIL> PSC2412_T_RELEASE_LOCATION_DETAIL { get; set; }
        public DbSet<PSC8010_M_PIPE_ITEM> PSC8010_M_PIPE_ITEM { get; set; }
        public DbSet<PSC2011_T_STOCK_DETAIL> PSC2011_T_STOCK_DETAIL { get; set; }
        public DbSet<PSC2210_T_MOVE_LOCATION> PSC2210_T_MOVE_LOCATION { get; set; }
        public DbSet<PSC2210_T_HHT_MOVE_IN> PSC2210_T_HHT_MOVE_IN { get; set; }
        public DbSet<PSC2210_T_HHT_MOVE_OUT> PSC2210_T_HHT_MOVE_OUT { get; set; }
        public DbSet<PSC2410_T_HHT_RELEASE> PSC2410_T_HHT_RELEASE { get; set; }
        public DbSet<PSC2411_T_RELEASE_DETAIL> PSC2411_T_RELEASE_DETAIL { get; set; }
        public DbSet<PSC2421_T_REQUEST_RELEASE> PSC2421_T_REQUEST_RELEASE { get; set; }
        public DbSet<PSC2414_T_RELEASE_HISTORY> PSC2414_T_RELEASE_HISTORY { get; set; }
        public DbSet<PSC2415_T_DELETE_HISTORY> PSC2415_T_DELETE_HISTORY {  get; set; }

        public virtual int SearchPipe(string heatNo)
        {
            var heatNoParameter = heatNo != null ?
                new ObjectParameter("heatNo", heatNo) :
                new ObjectParameter("heatNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SearchPipe", heatNoParameter);
        }
    
        public virtual ObjectResult<GetReceive_Result> GetReceive(string tranNo, ObjectParameter returned)
        {
            var tranNoParameter = tranNo != null ?
                new ObjectParameter("TranNo", tranNo) :
                new ObjectParameter("TranNo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetReceive_Result>("GetReceive", tranNoParameter, returned);
        }
    }
}
